config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale:/en|vi/ do
    root "static_pages#home"

    get  "/help",    to: "static_pages#help"

    get  "/signup",  to: "users#new"

    post "/signup",  to: "users#create"

    get "/login", to: "sessions#new"

    post "/login", to: "sessions#create"

    delete "/logout", to: "sessions#destroy"

    get "/password_resets", to: "password_resets#new"
  end

    resources :users

    resources :password_resets, only: [:create, :edit, :update]

    resources :account_activations, only: [:edit]

    resources :microposts, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :load_user, only: %i(edit update)
  before_action :check_expiration, only: %i(edit update)
  before_action :_get_user, only: %i(edit update)
  before_action :valid_user, only: %i(edit update)

  def new; end

  def create
    @user = User.find_by email: params[:password_reset][:email].downcase
    if @user
      @user.create_reset_digest
      @user.sent_password_reset_email
      flash[:info] = t "controllers.user.email.sent_with_password_reset"
      redirect_to root_url
    else
      flash[:danger] = t "contollers.user.email.address_not_found"
      render :new
    end
  end

  def edit; end

  def update
    if params[:user][:password].empty?
      update_empty
    elsif @user.update_attributes(user_params) && @user.update_attributes(reset_digest: nil)
      log_in @user
      flash[:success] = t "controllers.user.password_has_been_reset"
      redirect_to @user
    else
      not_change_password
    end
  end

  private

  def not_change_password
    render :edit
    flash[:danger] = t "controllers.user.password_has_not_reset"
  end

  def user_params
    params.require(:user).permit :password, :password_confirmation
  end

  def update_empty
    @user.error.add(:password, t("controllers.user.cant_be_empty"))
    render :edit
  end

  def check_expiration
    return unless @user.password_reset_expired?
    flash[:danger] = t "controllers.user.password_reset_has_expred"
    redirect_to new_password_reset_url
  end

  def load_user
    @user = User.find_by email: params[:email]
    return if @user
    flash[:danger] = t "controllers.user.not_found_user"
    render :new
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<%= provide(:title, t(".title")) %>
<h1><%= t(".reset_password") %></h1>

<div class="row">
  <div class="col-md-3 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t(".change_password"), class: "btn btn-lg btn-primary" %>
    <%= end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<%= provide :title, t(".forget_password") %>
<h1><%= t ".forget_password" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email, t(".email") %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.submit t(".submit"), class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>
</div>