config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale:/en|vi/ do
    root "static_pages#home"

    get  "/help",    to: "static_pages#help"

    get  "/signup",  to: "users#new"

    post "/signup",  to: "users#create"

    get "/login", to: "sessions#new"

    post "/login", to: "sessions#create"

    delete "/logout", to: "sessions#destroy"

    get "/password_resets", to: "password_resets#new"
  end

    resources :users

    resources :password_resets, only: [:create, :edit, :update]

    resources :account_activations, only: [:edit]

    resources :microposts, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= t ".lan" %></li>
      <li><%= link_to "English", locale: "en" %></li>
      <li><%= link_to "Vietnamese", locale: "vi" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".title"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(".user"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t(".account") %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to t(".logout"), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application",
      media: "all", "data-turbolinks-track": "reload" %>

    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>

    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>

    <div>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>